apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'

android {
    namespace 'pravbeseda'
    compileSdk 34

    compileOptions {
        sourceCompatibility 1.8
        targetCompatibility 1.8
    }

    buildFeatures {
        viewBinding true
    }

    defaultConfig {
        applicationId "ru.pravbeseda.currencyedittext"
        minSdkVersion 19
        targetSdkVersion 34
        versionCode VERSION_CODE.toInteger()
        versionName VERSION_NAME
    }
}

kotlin {
    compilerOptions {
        jvmTarget = org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_1_8
    }
}

dependencies {
    implementation project(':library')
    implementation 'androidx.core:core-ktx:1.10.1'
    implementation 'com.google.android.material:material:1.9.0'
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
}

apply from: '../spotless.gradle'
