plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
}

android {
    namespace 'pravbeseda'
    compileSdk 37

    compileOptions {
        sourceCompatibility 1.8
        targetCompatibility 1.8
    }

    buildFeatures {
        viewBinding true
    }

    defaultConfig {
        applicationId "ru.pravbeseda.currencyedittext"
        minSdkVersion 24
        targetSdkVersion 37
        versionCode VERSION_CODE.toInteger()
        versionName VERSION_NAME
    }
}

kotlin {
    compilerOptions {
        jvmTarget = org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_1_8
    }
}

dependencies {
    implementation project(':library')
    implementation libs.androidx.core.ktx
    implementation libs.material
    implementation libs.androidx.appcompat
    implementation libs.androidx.constraintlayout
}

apply from: '../spotless.gradle'
